### PR TITLE
Fix it again

### PR DESCRIPTION
**Pull request by thinkingsand**

### CODE REVIEW

**Review by jamesatjaminit — COMMENTED** [review]
Haven't you removed the grey colour?

**Comment by jamesatjaminit** [comment]
Why are we reverting? Can't we just specify the hex of a better grey?

**Comment by thinkingsand** [comment]
Wait, did you ever merge my old pr.

**Comment by jamesatjaminit** [comment]
The old one yes

**Comment by jamesatjaminit** [comment]
Not this one

**Comment by thinkingsand** [comment]
Revert it and we can change the minimum possible

**Comment by jamesatjaminit** [comment]
Okay

**Comment by thinkingsand** [comment]
Just merge this one

**Review by jamesatjaminit — APPROVED** [review]

**Pull request merged**
